from dataclasses import replace
from datetime import UTC, datetime, timedelta
from uuid import uuid4
from zoneinfo import ZoneInfo

import pytest
from conftest import FakeModels
from langchain_core.messages import AIMessage
from sqlalchemy import select
from test_agent import Chat, EmptyRetriever, settings
from test_crm_transactions import call, service
from test_crm_transactions import crm as crm_fixture

from appointments.agent_tools import local_booking_time
from appointments.models import Appointment
from context_agent.agent import Agent
from context_agent.notification_models import Notification
from context_agent.schemas import ChatInput, DomainError
from context_agent.tools import (
    APPOINTMENT_SERVICES,
    BOOK_APPOINTMENT,
    ToolContext,
    available_tools,
    execute,
)
from crm.models import Contact, Customer, Lead, SocialIdentity
from crm.service import capture_incoming
from modules.models import BusinessModules
from super_admin.businesses.models import Business

crm = crm_fixture


def context(c, channel="web", external_user_id="visitor:booking-test", **changes):
    return ToolContext(
        c.a.business.slug,
        changes.pop("request_id", uuid4()),
        "book-test",
        c.settings,
        db=c.db,
        channel=channel,
        external_user_id=external_user_id,
        **changes,
    )


def booking(s, **changes):
    date = (datetime.now(ZoneInfo("Asia/Kolkata")) + timedelta(days=3)).date().isoformat()
    return {
        "service_id": s["id"],
        "patient_name": "Test Patient",
        "date": date,
        "time": "11:30",
        "phone": "+91 98765 43210",
        "concern": "Consultation for teeth alignment",
        **changes,
    }


async def rows(c, model):
    async with c.db.transaction() as session:
        return list((await session.scalars(select(model))).all())


async def test_booking_appears_in_portal_and_queues_one_notification(crm):
    c = crm
    s = await service(c)
    args, ctx = booking(s), context(c)
    first = await execute(BOOK_APPOINTMENT, args, ctx)
    assert first["ok"] is True
    assert first["status"] == "scheduled" and first["requires_staff_confirmation"] is True
    assert first["availability_checked"] is False
    assert first["scheduled_at"] == f"{args['date']}T11:30:00+05:30"
    assert first["price"] == "75.00"
    listed = await call(c, "GET", "/appointments")
    assert listed["total"] == 1
    saved = listed["items"][0]
    assert saved["id"] == first["appointment_id"]
    assert "Patient: Test Patient" in saved["notes"] and "Channel: web" in saved["notes"]
    assert args["concern"] in saved["notes"]
    customer = await call(c, "GET", "/customers/" + saved["customer_id"])
    assert customer["phone"] == "+919876543210"
    assert customer["social_identities"] == []
    assert len(await rows(c, Customer)) == len(await rows(c, Notification)) == 1
    assert (await rows(c, Notification))[0].url == "/appointments/" + saved["id"]


async def test_same_turn_retry_and_second_confirmation_do_not_duplicate(crm):
    c = crm
    s = await service(c)
    args, ctx = booking(s), context(c)
    first = await execute(BOOK_APPOINTMENT, args, ctx)
    # Call IDs are generated by the model; they are not idempotency keys.
    assert await execute(BOOK_APPOINTMENT, args, replace(ctx, call_id="retry")) == first
    repeated = await execute(BOOK_APPOINTMENT, args, replace(ctx, request_id=uuid4()))
    assert repeated == first
    changed = await execute(BOOK_APPOINTMENT, {**args, "time": "12:00"}, ctx)
    assert changed["ok"] is False and changed["code"] == "request_changed"
    assert len(await rows(c, Appointment)) == len(await rows(c, Notification)) == 1


async def test_retry_keeps_price_snapshot_and_does_not_rebook_cancelled(crm):
    c = crm
    s = await service(c)
    args, ctx = booking(s), context(c)
    first = await execute(BOOK_APPOINTMENT, args, ctx)
    await call(c, "PATCH", "/services/" + s["id"], {"price": "900", "status": "archived"})
    await call(c, "PATCH", "/appointments/" + first["appointment_id"], {"status": "cancelled"})
    retry = await execute(BOOK_APPOINTMENT, args, ctx)
    assert retry["ok"] is True and retry["status"] == "cancelled"
    assert retry["price"] == "75.00"
    assert len(await rows(c, Appointment)) == 1


async def test_family_patients_sharing_phone_can_book_separately(crm):
    c = crm
    s = await service(c)
    first = await execute(BOOK_APPOINTMENT, booking(s), context(c))
    second = await execute(BOOK_APPOINTMENT, booking(s, patient_name="Another Patient"), context(c))
    assert first["appointment_id"] != second["appointment_id"]
    assert len(await rows(c, Appointment)) == 2
    assert len(await rows(c, Customer)) == 1


@pytest.mark.parametrize("channel", ["instagram", "whatsapp", "telegram", "facebook"])
async def test_social_booking_uses_real_sender_without_requiring_phone(crm, channel):
    c = crm
    s = await service(c)
    ctx = context(c, channel=channel, external_user_id="sender-123")
    request = ChatInput(
        message="Please book a consultation",
        request_id=ctx.request_id,
        channel=channel,
        external_user_id=ctx.external_user_id,
    )
    await capture_incoming(c.db, ctx.tenant_id, request)
    args = booking(s)
    args.pop("phone")
    result = await execute(BOOK_APPOINTMENT, args, ctx)
    assert result["ok"] is True
    identity = (await rows(c, SocialIdentity))[0]
    assert identity.platform == channel and identity.external_id == "sender-123"
    lead = (await rows(c, Lead))[0]
    assert lead.customer_id is not None and lead.converted_at is not None
    assert (await rows(c, Appointment))[0].lead_id == lead.id
    assert (await rows(c, Contact))[0].phone is None


async def test_web_booking_converts_the_existing_anonymous_lead(crm):
    c = crm
    s, ctx = await service(c), context(c)
    await capture_incoming(
        c.db,
        ctx.tenant_id,
        ChatInput(
            message="Book please",
            request_id=uuid4(),
            channel="web",
            external_user_id=ctx.external_user_id,
        ),
    )
    result = await execute(BOOK_APPOINTMENT, booking(s), ctx)
    assert result["ok"] is True
    assert len(await rows(c, Lead)) == len(await rows(c, Contact)) == 1
    assert (await rows(c, Lead))[0].customer_id == (await rows(c, Customer))[0].id


@pytest.mark.parametrize("channel", ["web", "admin_chat"])
async def test_non_social_session_is_not_a_contact(crm, channel):
    c = crm
    s = await service(c)
    args = booking(s)
    args.pop("phone")
    result = await execute(BOOK_APPOINTMENT, args, context(c, channel=channel))
    assert result["ok"] is False and result["code"] == "contact_required"
    assert not await rows(c, Customer)


@pytest.mark.parametrize(
    "changes,code",
    [
        ({"date": "2000-01-01"}, "past_appointment"),
        ({"date": "2030-02-30"}, "invalid_booking_time"),
        ({"time": "25:00"}, "invalid_booking_time"),
        ({"phone": "9876543210"}, "invalid_booking_details"),
        ({"patient_name": " "}, "invalid_booking_details"),
    ],
)
async def test_invalid_bookings_never_create_customer_or_notification(crm, changes, code):
    c = crm
    result = await execute(BOOK_APPOINTMENT, booking(await service(c), **changes), context(c))
    assert result["ok"] is False and result["code"] == code
    for model in [Appointment, Customer, Contact, Notification]:
        assert not await rows(c, model)


@pytest.mark.parametrize("state", ["inactive", "archived"])
async def test_inactive_service_cannot_be_booked(crm, state):
    c = crm
    result = await execute(BOOK_APPOINTMENT, booking(await service(c, status=state)), context(c))
    assert result["ok"] is False and result["code"] == "service_unavailable"
    assert not await rows(c, Customer)


async def test_catalog_and_booking_are_isolated_to_business(crm):
    c = crm
    own = await service(c)
    foreign = await call(
        c, "POST", "/services", {"name": "Other business", "price": "1"}, owner=c.b, code=201
    )
    await service(c, name="Archived", status="archived")
    catalog = await execute(APPOINTMENT_SERVICES, {}, context(c))
    assert catalog["ok"] and [s["id"] for s in catalog["services"]] == [own["id"]]
    assert catalog["timezone"] == "Asia/Kolkata"
    assert "customer_id" not in str(catalog)
    result = await execute(BOOK_APPOINTMENT, booking(foreign), context(c))
    assert result["ok"] is False and result["code"] == "record_not_found"
    with pytest.raises(Exception):
        await execute(BOOK_APPOINTMENT, booking(own, tenant_id=c.b.business.slug), context(c))
    with pytest.raises(Exception):
        await execute(BOOK_APPOINTMENT, booking(own, external_user_id="victim"), context(c))
    assert not await rows(c, Customer)


@pytest.mark.parametrize("disable", ["appointments", "customers", "business"])
async def test_disabled_business_or_module_removes_and_blocks_tools(crm, disable):
    c = crm
    s = await service(c)
    async with c.db.transaction() as session:
        tools = await available_tools(session, c.a.business.slug, [])
        assert BOOK_APPOINTMENT.name in tools and APPOINTMENT_SERVICES.name in tools
        if disable == "business":
            (await session.get(Business, c.a.business.id)).status = "suspended"
        else:
            modules = await session.get(BusinessModules, c.a.business.id)
            setattr(
                modules, "service_appointments" if disable == "appointments" else "customers", False
            )
            if disable == "customers":
                # The database itself forbids services/orders without Customers.
                modules.service_appointments = modules.product_orders = False
    async with c.db.transaction() as session:
        tools = await available_tools(session, c.a.business.slug, [])
        assert BOOK_APPOINTMENT.name not in tools and APPOINTMENT_SERVICES.name not in tools
    # Even an already-issued model tool call is rechecked under the transaction lock.
    result = await execute(BOOK_APPOINTMENT, booking(s), context(c))
    assert result["ok"] is False
    assert not await rows(c, Appointment)


async def test_notification_failure_rolls_back_entire_booking(crm, monkeypatch):
    c = crm

    async def fail(*args):
        raise RuntimeError("injected failure")

    monkeypatch.setattr("appointments.service.queue_notification", fail)
    result = await execute(BOOK_APPOINTMENT, booking(await service(c)), context(c))
    assert result["ok"] is False
    assert not await rows(c, Appointment)
    assert not await rows(c, Customer)
    assert not await rows(c, Contact)


async def test_agent_books_from_catalog_without_retrieval_or_tool_sync(crm):
    c = crm
    s = await service(c)
    models = FakeModels()
    models.chat = Chat(
        [
            AIMessage(
                content="",
                tool_calls=[{"name": APPOINTMENT_SERVICES.name, "args": {}, "id": "list"}],
            ),
            AIMessage(
                content="",
                tool_calls=[{"name": BOOK_APPOINTMENT.name, "args": booking(s), "id": "book"}],
            ),
            AIMessage(content="Your appointment is saved, pending staff confirmation."),
        ]
    )
    result = await Agent(c.db, models, EmptyRetriever(), settings()).run(
        c.a.business.slug,
        ChatInput(
            message="Please book my consultation",
            request_id=uuid4(),
            channel="admin_chat",
            external_user_id="admin-session",
        ),
    )
    assert result["outcome"] == "answered"
    assert [r["result"]["ok"] for r in result["tool_results"]] == [True, True]
    assert len(await rows(c, Appointment)) == 1
    prompt = models.chat.last_messages[0].content
    assert "CURRENT BUSINESS TIME:" in prompt and "Asia/Kolkata" in prompt
    assert "pending clinic/staff confirmation" in prompt


def test_timezone_conversion_and_dst_are_explicit():
    assert local_booking_time("2030-01-02", "10:00", "Asia/Kolkata") == datetime(
        2030, 1, 2, 4, 30, tzinfo=UTC
    )
    assert local_booking_time("2030-01-02", "10:00", "America/New_York") == datetime(
        2030, 1, 2, 15, tzinfo=UTC
    )
    for date, time in [("2030-03-10", "02:30"), ("2030-11-03", "01:30")]:
        with pytest.raises(DomainError, match="unambiguous"):
            local_booking_time(date, time, "America/New_York")
